<?php
declare(strict_types=1);require_once dirname(__DIR__).'/config/bootstrap.php';require_permission('sales.view');$q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'completed');$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));$page=max(1,(int)($_GET['page']??1));$per=30;$where=['1=1'];$params=[];if($q!==''){$where[]='(s.sale_no LIKE :q OR c.name LIKE :q OR u.full_name LIKE :q)';$params[':q']='%'.$q.'%';}if(in_array($status,['completed','held','voided'],true)){$where[]='s.status=:status';$params[':status']=$status;}if($from!==''){$where[]='s.sale_date>=:from';$params[':from']=$from.' 00:00:00';}if($to!==''){$where[]='s.sale_date<DATE_ADD(:to,INTERVAL 1 DAY)';$params[':to']=$to.' 00:00:00';}$ws=implode(' AND ',$where);$cnt=db()->prepare("SELECT COUNT(*) FROM sales s LEFT JOIN customers c ON c.id=s.customer_id INNER JOIN users u ON u.id=s.created_by WHERE $ws");$cnt->execute($params);$total=(int)$cnt->fetchColumn();$pages=max(1,(int)ceil($total/$per));$page=min($page,$pages);$off=($page-1)*$per;$st=db()->prepare("SELECT s.*,c.name customer_name,u.full_name cashier FROM sales s LEFT JOIN customers c ON c.id=s.customer_id INNER JOIN users u ON u.id=s.created_by WHERE $ws ORDER BY s.sale_date DESC,s.id DESC LIMIT $per OFFSET $off");$st->execute($params);$rows=$st->fetchAll();$sum=db()->prepare("SELECT COALESCE(SUM(s.total_amount),0) sales,COALESCE(SUM(s.gross_profit),0) profit,COUNT(*) transactions FROM sales s LEFT JOIN customers c ON c.id=s.customer_id INNER JOIN users u ON u.id=s.created_by WHERE $ws");$sum->execute($params);$summary=$sum->fetch()?:[];
$pageTitle='Sales';$pageStyles=['admin.css','commerce.css'];require BASE_PATH.'/includes/header.php';require BASE_PATH.'/includes/sidebar.php';?>
<style>
.filter-bar{
    display:flex;
    flex-wrap:wrap;
    gap:10px;
    align-items:center;
}
.filter-bar .button{
    flex:0 0 auto;
    white-space:nowrap;
}
</style>
<div class="app-main"><?php require BASE_PATH.'/includes/navbar.php';?><main class="content"><?php require BASE_PATH.'/includes/alerts.php';?><div class="page-toolbar"><div><span class="eyebrow">Sales history</span><h2>Sales</h2><p>Completed, held and voided transactions.</p></div><?php if(user_can('pos.use')):?><a class="button button--primary" href="<?=e(app_url('pos/index'))?>">Open POS</a><?php endif;?></div><section class="mini-metric-grid"><article class="mini-metric"><span>Sales total</span><strong><?=e(money($summary['sales']??0))?></strong></article><article class="mini-metric"><span>Gross profit</span><strong><?=e(money($summary['profit']??0))?></strong></article><article class="mini-metric"><span>Transactions</span><strong><?=e((string)($summary['transactions']??0))?></strong></article></section><section class="panel-card table-panel"><form class="filter-bar" method="get"><div class="filter-search"><input name="q" value="<?=e($q)?>" placeholder="Receipt, customer or cashier"></div><select name="status"><option value="completed" <?=$status==='completed'?'selected':''?>>Completed</option><option value="held" <?=$status==='held'?'selected':''?>>Held</option><option value="voided" <?=$status==='voided'?'selected':''?>>Voided</option></select><input type="date" name="from" value="<?=e($from)?>"><input type="date" name="to" value="<?=e($to)?>"><button class="button button--secondary">Filter</button><a class="button button--secondary" href="<?=e(app_url('sales/index'))?>">Reset</a><a class="button button--primary" href="<?=e(app_url('sales/report_pdf?'.http_build_query(['q'=>$q,'status'=>$status,'from'=>$from,'to'=>$to])))?>">Download PDF</a></form><div class="table-wrap"><table class="data-table"><thead><tr><th>Sale</th><th>Date</th><th>Customer</th><th>Cashier</th><th>Total</th><th>Paid</th><th>Balance</th><th>Payment</th><th></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="9"><div class="empty-state"><strong>No sales found</strong></div></td></tr><?php else:foreach($rows as$s):?><tr><td><strong><?=e($s['sale_no'])?></strong><small class="table-note"><?=e(ucfirst($s['status']))?></small></td><td><?=e(format_datetime($s['sale_date']))?></td><td><?=e($s['customer_name']?:'Walk-in')?></td><td><?=e($s['cashier'])?></td><td><?=e(money($s['total_amount']))?></td><td><?=e(money($s['amount_paid']))?></td><td><?=e(money($s['balance_due']))?></td><td><?=e(ucfirst($s['payment_status']))?></td><td class="table-action-cell"><a class="table-action" href="<?=e(app_url('sales/view?id='.(int)$s['id']))?>">View</a></td></tr><?php endforeach;endif;?></tbody></table></div><div class="table-footer"><span>Showing <?=$total===0?0:$off+1?>–<?=min($off+$per,$total)?> of <?=$total?></span></div></section></main></div><?php require BASE_PATH.'/includes/footer.php';?>
