<?php
declare(strict_types=1);require_once dirname(__DIR__).'/config/bootstrap.php';require_permission('purchases.create');
$suppliers=db()->query('SELECT id,name FROM suppliers WHERE status="active" ORDER BY name')->fetchAll();$products=db()->query('SELECT p.id,p.name,p.sku,p.buying_price,u.short_name,u.allows_decimal FROM products p INNER JOIN units u ON u.id=p.unit_id WHERE p.status="active" ORDER BY p.name')->fetchAll();$paymentMethods=db()->query('SELECT id,name,method_type,requires_reference FROM payment_methods WHERE is_active=1 AND method_type<>"credit" ORDER BY sort_order,name')->fetchAll();$errors=[];$supplierDefault=(int)($_GET['supplier']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 require_valid_csrf();$supplierId=(int)($_POST['supplier_id']??0);$invoice=trim((string)($_POST['invoice_reference']??''));$date=trim((string)($_POST['purchase_date']??''));$notes=trim((string)($_POST['notes']??''));$discountRaw=(string)($_POST['discount_amount']??'0');$paidRaw=(string)($_POST['amount_paid']??'0');$paymentMethodId=(int)($_POST['payment_method_id']??0);$paymentRef=trim((string)($_POST['payment_reference']??''));$ids=$_POST['product_id']??[];$qtys=$_POST['quantity']??[];$costs=$_POST['unit_cost']??[];
 $sup=db()->prepare('SELECT id FROM suppliers WHERE id=:id AND status="active"');$sup->execute([':id'=>$supplierId]);if(!$sup->fetchColumn())$errors[]='Choose a valid supplier.';
 try{$purchaseDate=(new DateTimeImmutable($date?:'now'))->format('Y-m-d H:i:s');$discountCents=money_to_cents($discountRaw);$paidCents=money_to_cents($paidRaw);if($discountCents<0||$paidCents<0)throw new InvalidArgumentException();}catch(Throwable){$errors[]='Enter valid purchase amounts and date.';$discountCents=$paidCents=0;$purchaseDate=date('Y-m-d H:i:s');}
 $items=[];$subtotalCents=0;$seen=[];
 if(!is_array($ids)||!is_array($qtys)||!is_array($costs))$errors[]='Add at least one purchase item.';else{
  $count=max(count($ids),count($qtys),count($costs));
  for($i=0;$i<$count;$i++){ $pid=(int)($ids[$i]??0); if($pid<=0)continue; if(isset($seen[$pid])){$errors[]='The same product appears more than once.';continue;}$seen[$pid]=true;
   $ps=db()->prepare('SELECT p.id,p.name,u.allows_decimal FROM products p INNER JOIN units u ON u.id=p.unit_id WHERE p.id=:id AND p.status="active"');$ps->execute([':id'=>$pid]);$product=$ps->fetch();if(!$product){$errors[]='One selected product is unavailable.';continue;}
   try{$q=quantity_to_milli((string)($qtys[$i]??'0'));$cost4=decimal4_to_units((string)($costs[$i]??'0'));if($q<=0||$cost4<0)throw new InvalidArgumentException();if((int)$product['allows_decimal']===0&&$q%1000!==0)throw new RuntimeException($product['name'].' only accepts whole quantities.');$line=line_cost_cents($q,$cost4);$subtotalCents+=$line;$items[]=['product_id'=>$pid,'quantity'=>$q,'cost4'=>$cost4,'line'=>$line];}catch(Throwable $e){$errors[]=$e instanceof RuntimeException?$e->getMessage():'Enter valid purchase quantities and costs.';}
  }
 }
 if(!$items)$errors[]='Add at least one valid purchase item.';$totalCents=max(0,$subtotalCents-$discountCents);if($discountCents>$subtotalCents)$errors[]='Discount cannot exceed the purchase subtotal.';if($paidCents>$totalCents)$errors[]='Amount paid cannot exceed the purchase total.';
 $method=null;if($paidCents>0){$method=payment_method_by_id(db(),$paymentMethodId);if(!$method||$method['method_type']==='credit')$errors[]='Choose a valid payment method.';}
 if(!$errors){$pdo=db();try{$pdo->beginTransaction();$no=next_document_number($pdo,'purchase');$balance=$totalCents-$paidCents;$payStatus=$paidCents===0?'unpaid':($balance===0?'paid':'partial');$ins=$pdo->prepare('INSERT INTO purchases(branch_id,supplier_id,purchase_no,invoice_reference,purchase_date,status,subtotal,discount_amount,total_amount,amount_paid,balance_due,payment_status,notes,created_by) VALUES(:branch,:supplier,:no,:invoice,:date,"ordered",:subtotal,:discount,:total,:paid,:balance,:ps,:notes,:user)');$ins->execute([':branch'=>current_branch_id(),':supplier'=>$supplierId,':no'=>$no,':invoice'=>$invoice?:null,':date'=>$purchaseDate,':subtotal'=>cents_to_decimal($subtotalCents),':discount'=>cents_to_decimal($discountCents),':total'=>cents_to_decimal($totalCents),':paid'=>cents_to_decimal($paidCents),':balance'=>cents_to_decimal($balance),':ps'=>$payStatus,':notes'=>$notes?:null,':user'=>(int)current_user()['id']]);$purchaseId=(int)$pdo->lastInsertId();
 foreach($items as$item){$ii=$pdo->prepare('INSERT INTO purchase_items(purchase_id,product_id,quantity,unit_cost,discount_amount,line_total) VALUES(:purchase,:product,:qty,:cost,0.00,:total)');$ii->execute([':purchase'=>$purchaseId,':product'=>$item['product_id'],':qty'=>milli_to_decimal($item['quantity']),':cost'=>units4_to_decimal($item['cost4']),':total'=>cents_to_decimal($item['line'])]);}
 if($paidCents>0&&$method){$pp=$pdo->prepare('INSERT INTO purchase_payments(purchase_id,payment_method_id,amount,reference_no,paid_at,created_by) VALUES(:purchase,:method,:amount,:ref,NOW(),:user)');$pp->execute([':purchase'=>$purchaseId,':method'=>$paymentMethodId,':amount'=>cents_to_decimal($paidCents),':ref'=>$paymentRef?:null,':user'=>(int)current_user()['id']]);if($method['method_type']==='cash'){$cm=$pdo->prepare('INSERT INTO cash_movements(cash_session_id,branch_id,movement_type,reference_type,reference_id,amount,description,created_by) VALUES(:session,:branch,"cash_out","purchase",:id,:amount,:description,:user)');$cm->execute([':session'=>active_cash_session_id($pdo,(int)current_user()['id'],current_branch_id()),':branch'=>current_branch_id(),':id'=>$purchaseId,':amount'=>cents_to_decimal(-$paidCents),':description'=>'Purchase payment '.$no,':user'=>(int)current_user()['id']]);}}
 $pdo->commit();audit_log('purchase_created','purchases',$purchaseId,'Purchase created: '.$no.'.',null,['supplier_id'=>$supplierId,'total'=>cents_to_decimal($totalCents)]);flash('success','Purchase '.$no.' created. Receive the stock when it arrives.');redirect('purchases/view?id='.$purchaseId);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();error_log('Purchase create failed: '.$e->getMessage());$errors[]='The purchase could not be saved.';}}
}
$pageTitle='New Purchase';$pageStyles=['admin.css','commerce.css'];$pageScripts=['purchase.js'];require BASE_PATH.'/includes/header.php';require BASE_PATH.'/includes/sidebar.php';?>
<div class="app-main"><?php require BASE_PATH.'/includes/navbar.php';?><main class="content"><div class="page-toolbar"><div><a class="back-link" href="<?=e(app_url('purchases/index'))?>">← Purchases</a><h2>New purchase</h2><p>Create the supplier purchase now; inventory increases only when stock is received.</p></div></div><?php foreach($errors as$error):?><div class="app-alert app-alert--danger"><?=e($error)?></div><?php endforeach;?>
<form method="post" class="form-card" data-purchase-builder><?=csrf_field()?><div class="form-section"><div class="form-grid"><div class="field"><label>Supplier</label><select name="supplier_id" required><option value="">Select supplier</option><?php foreach($suppliers as$s):?><option value="<?=e((string)$s['id'])?>" <?=$supplierDefault===(int)$s['id']?'selected':''?>><?=e($s['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Purchase date</label><input type="date" name="purchase_date" value="<?=e(date('Y-m-d'))?>" required></div><div class="field field--span-2"><label>Supplier invoice / reference</label><input name="invoice_reference" maxlength="120"></div></div></div>
<div class="form-section"><div class="form-section__heading form-heading-row"><div><span class="eyebrow">Items</span><h3>Products being purchased</h3></div><button class="button button--secondary" type="button" data-add-purchase-row>+ Add row</button></div><div class="table-wrap"><table class="data-table purchase-builder-table"><thead><tr><th>Product</th><th>Quantity</th><th>Unit cost</th><th>Line total</th><th></th></tr></thead><tbody data-purchase-rows></tbody></table></div></div>
<div class="form-section"><div class="form-grid"><div class="field"><label>Purchase discount</label><input type="number" name="discount_amount" min="0" step="0.01" value="0.00"></div><div class="field"><label>Amount paid now</label><input type="number" name="amount_paid" min="0" step="0.01" value="0.00"></div><div class="field"><label>Payment method</label><select name="payment_method_id"><option value="0">Select if paying now</option><?php foreach($paymentMethods as$m):?><option value="<?=e((string)$m['id'])?>"><?=e($m['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Payment reference</label><input name="payment_reference" maxlength="120" placeholder="M-Pesa / bank / card reference"></div><div class="field field--span-2"><label>Notes</label><textarea name="notes" rows="3"></textarea></div></div><div class="purchase-summary"><span>Purchase total</span><strong><?=e(APP_CURRENCY_SYMBOL)?> <span data-purchase-total>0.00</span></strong></div></div>
<div class="form-actions"><a class="button button--ghost" href="<?=e(app_url('purchases/index'))?>">Cancel</a><button class="button button--primary">Create purchase</button></div></form>
<script>window.PURCHASE_PRODUCTS=<?=json_encode($products,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?>;</script></main></div><?php require BASE_PATH.'/includes/footer.php';?>
