<?php
declare(strict_types=1);require_once dirname(__DIR__).'/config/bootstrap.php';require_permission('purchases.view');
$q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'');$supplierId=(int)($_GET['supplier']??0);$page=max(1,(int)($_GET['page']??1));$per=20;$where=['1=1'];$params=[];
if($q!==''){$where[]='(p.purchase_no LIKE :q OR p.invoice_reference LIKE :q OR s.name LIKE :q)';$params[':q']='%'.$q.'%';}if(in_array($status,['draft','ordered','partially_received','received','cancelled'],true)){$where[]='p.status=:status';$params[':status']=$status;}if($supplierId>0){$where[]='p.supplier_id=:supplier';$params[':supplier']=$supplierId;}$ws=implode(' AND ',$where);$c=db()->prepare("SELECT COUNT(*) FROM purchases p INNER JOIN suppliers s ON s.id=p.supplier_id WHERE $ws");$c->execute($params);$total=(int)$c->fetchColumn();$pages=max(1,(int)ceil($total/$per));$page=min($page,$pages);$off=($page-1)*$per;
$st=db()->prepare("SELECT p.*,s.name supplier_name,u.full_name created_by_name FROM purchases p INNER JOIN suppliers s ON s.id=p.supplier_id INNER JOIN users u ON u.id=p.created_by WHERE $ws ORDER BY p.purchase_date DESC,p.id DESC LIMIT $per OFFSET $off");$st->execute($params);$purchases=$st->fetchAll();$suppliers=db()->query('SELECT id,name FROM suppliers WHERE status="active" ORDER BY name')->fetchAll();$sum=db()->query('SELECT COALESCE(SUM(total_amount),0) total_value,COALESCE(SUM(balance_due),0) total_balance,COUNT(CASE WHEN status IN("ordered","partially_received") THEN 1 END) pending FROM purchases WHERE status<>"cancelled"')->fetch()?:[];
$pageTitle='Purchases';$pageStyles=['admin.css','commerce.css'];require BASE_PATH.'/includes/header.php';require BASE_PATH.'/includes/sidebar.php';?>
<div class="app-main"><?php require BASE_PATH.'/includes/navbar.php';?><main class="content"><?php require BASE_PATH.'/includes/alerts.php';?><div class="page-toolbar"><div><span class="eyebrow">Stock acquisition</span><h2>Purchases</h2><p>Order, receive and pay supplier stock.</p></div><?php if(user_can('purchases.create')):?><a class="button button--primary" href="<?=e(app_url('purchases/add'))?>">+ New purchase</a><?php endif;?></div>
<section class="mini-metric-grid"><article class="mini-metric"><span>Total purchases</span><strong><?=e((string)$total)?></strong></article><article class="mini-metric"><span>Purchase value</span><strong><?=e(money($sum['total_value']??0))?></strong></article><article class="mini-metric"><span>Supplier balance</span><strong><?=e(money($sum['total_balance']??0))?></strong></article><article class="mini-metric"><span>Awaiting receipt</span><strong><?=e((string)($sum['pending']??0))?></strong></article></section>
<section class="panel-card table-panel"><form class="filter-bar" method="get"><div class="filter-search"><input name="q" value="<?=e($q)?>" placeholder="Purchase no, invoice or supplier"></div><select name="supplier"><option value="0">All suppliers</option><?php foreach($suppliers as$s):?><option value="<?=e((string)$s['id'])?>" <?=$supplierId===(int)$s['id']?'selected':''?>><?=e($s['name'])?></option><?php endforeach;?></select><select name="status"><option value="">All statuses</option><?php foreach(['ordered','partially_received','received','cancelled']as$v):?><option value="<?=$v?>" <?=$status===$v?'selected':''?>><?=e(ucwords(str_replace('_',' ',$v)))?></option><?php endforeach;?></select><button class="button button--secondary">Filter</button></form><div class="table-wrap"><table class="data-table"><thead><tr><th>Purchase</th><th>Supplier</th><th>Date</th><th>Status</th><th>Payment</th><th>Total</th><th>Balance</th><th></th></tr></thead><tbody><?php if(!$purchases):?><tr><td colspan="8"><div class="empty-state"><strong>No purchases found</strong></div></td></tr><?php else:foreach($purchases as$p):?><tr><td><strong><?=e($p['purchase_no'])?></strong><small class="table-note"><?=e($p['invoice_reference']?:'No supplier invoice')?></small></td><td><?=e($p['supplier_name'])?></td><td><?=e(format_datetime($p['purchase_date'],'d M Y'))?></td><td><span class="status-badge status-badge--<?=e($p['status']==='received'?'active':($p['status']==='cancelled'?'inactive':'locked'))?>"><?=e(ucwords(str_replace('_',' ',$p['status'])))?></span></td><td><?=e(ucfirst($p['payment_status']))?></td><td><?=e(money($p['total_amount']))?></td><td><?=e(money($p['balance_due']))?></td><td class="table-action-cell"><a class="table-action" href="<?=e(app_url('purchases/view?id='.(int)$p['id']))?>">View</a></td></tr><?php endforeach;endif;?></tbody></table></div><div class="table-footer"><span>Showing <?=$total===0?0:$off+1?>–<?=min($off+$per,$total)?> of <?=$total?></span></div></section>
</main></div><?php require BASE_PATH.'/includes/footer.php';?>
