<?php
declare(strict_types=1);require_once dirname(__DIR__).'/config/bootstrap.php';require_permission('purchases.view');$id=(int)($_GET['id']??0);$st=db()->prepare('SELECT p.*,s.name supplier_name,s.phone supplier_phone,u.full_name created_by_name FROM purchases p INNER JOIN suppliers s ON s.id=p.supplier_id INNER JOIN users u ON u.id=p.created_by WHERE p.id=:id');$st->execute([':id'=>$id]);$p=$st->fetch();if(!$p){flash('error','Purchase not found.');redirect('purchases/index.php');}
$it=db()->prepare('SELECT pi.*,pr.name product_name,pr.sku,u.short_name FROM purchase_items pi INNER JOIN products pr ON pr.id=pi.product_id INNER JOIN units u ON u.id=pr.unit_id WHERE pi.purchase_id=:id ORDER BY pi.id');$it->execute([':id'=>$id]);$items=$it->fetchAll();$pay=db()->prepare('SELECT pp.*,pm.name method_name,usr.full_name FROM purchase_payments pp INNER JOIN payment_methods pm ON pm.id=pp.payment_method_id INNER JOIN users usr ON usr.id=pp.created_by WHERE pp.purchase_id=:id ORDER BY pp.id DESC');$pay->execute([':id'=>$id]);$payments=$pay->fetchAll();
$pageTitle=$p['purchase_no'];$pageStyles=['admin.css','commerce.css'];require BASE_PATH.'/includes/header.php';require BASE_PATH.'/includes/sidebar.php';?>
<div class="app-main"><?php require BASE_PATH.'/includes/navbar.php';?><main class="content"><?php require BASE_PATH.'/includes/alerts.php';?><div class="page-toolbar"><div><a class="back-link" href="<?=e(app_url('purchases/index.php'))?>">← Purchases</a><h2><?=e($p['purchase_no'])?></h2><p><?=e($p['supplier_name'])?> · <?=e(format_datetime($p['purchase_date'],'d M Y'))?></p></div><div class="toolbar-actions"><?php if(user_can('purchases.pay')&&(float)$p['balance_due']>0&&$p['status']!=='cancelled'):?><a class="button button--secondary" href="<?=e(app_url('purchases/payment.php?id='.$id))?>">Record payment</a><?php endif;?><?php if(user_can('purchases.receive')&&in_array($p['status'],['ordered','partially_received'],true)):?><a class="button button--primary" href="<?=e(app_url('purchases/receive.php?id='.$id))?>">Receive stock</a><?php endif;?></div></div>
<section class="mini-metric-grid"><article class="mini-metric"><span>Status</span><strong class="metric-text"><?=e(ucwords(str_replace('_',' ',$p['status'])))?></strong></article><article class="mini-metric"><span>Total</span><strong><?=e(money($p['total_amount']))?></strong></article><article class="mini-metric"><span>Paid</span><strong><?=e(money($p['amount_paid']))?></strong></article><article class="mini-metric"><span>Balance</span><strong><?=e(money($p['balance_due']))?></strong></article></section>
<section class="panel-card table-panel"><div class="panel-card__header"><span class="eyebrow">Purchase items</span><h3>Ordered stock</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Product</th><th>Ordered</th><th>Received</th><th>Unit cost</th><th>Total</th></tr></thead><tbody><?php foreach($items as$i):?><tr><td><strong><?=e($i['product_name'])?></strong><small class="table-note"><?=e($i['sku'])?></small></td><td><?=e(format_quantity($i['quantity']))?> <?=e($i['short_name'])?></td><td><?=e(format_quantity($i['quantity_received']))?> <?=e($i['short_name'])?></td><td><?=e(money($i['unit_cost']))?></td><td><?=e(money($i['line_total']))?></td></tr><?php endforeach;?></tbody></table></div><div class="purchase-total-block"><div><span>Subtotal</span><strong><?=e(money($p['subtotal']))?></strong></div><div><span>Discount</span><strong>-<?=e(money($p['discount_amount']))?></strong></div><div class="is-total"><span>Total</span><strong><?=e(money($p['total_amount']))?></strong></div></div></section>
<section class="detail-two-column section-gap"><article class="panel-card"><div class="panel-card__header"><h3>Purchase details</h3></div><dl class="detail-list"><div><dt>Supplier invoice</dt><dd><?=e($p['invoice_reference']?:'—')?></dd></div><div><dt>Created by</dt><dd><?=e($p['created_by_name'])?></dd></div><div><dt>Payment status</dt><dd><?=e(ucfirst($p['payment_status']))?></dd></div><div><dt>Notes</dt><dd><?=e($p['notes']?:'—')?></dd></div></dl></article><article class="panel-card"><div class="panel-card__header"><h3>Payments</h3></div><div class="simple-list"><?php if(!$payments):?><div class="empty-state compact"><strong>No payments recorded</strong></div><?php else:foreach($payments as$payment):?><div class="simple-list__row"><div><strong><?=e($payment['method_name'])?> · <?=e(money($payment['amount']))?></strong><span><?=e(format_datetime($payment['paid_at']))?><?= $payment['reference_no']?' · '.e($payment['reference_no']):''?></span></div></div><?php endforeach;endif;?></div></article></section>
</main></div><?php require BASE_PATH.'/includes/footer.php';?>
