<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php'; require_permission('suppliers.view');
$q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'active');if(!in_array($status,['active','inactive','all'],true))$status='active';$page=max(1,(int)($_GET['page']??1));$per=20;$where=['1=1'];$params=[];
if($q!==''){$where[]='(s.name LIKE :q OR s.contact_person LIKE :q OR s.phone LIKE :q OR s.email LIKE :q)';$params[':q']='%'.$q.'%';}if($status!=='all'){$where[]='s.status=:status';$params[':status']=$status;}$ws=implode(' AND ',$where);$c=db()->prepare("SELECT COUNT(*) FROM suppliers s WHERE $ws");$c->execute($params);$total=(int)$c->fetchColumn();$pages=max(1,(int)ceil($total/$per));$page=min($page,$pages);$off=($page-1)*$per;
$st=db()->prepare("SELECT s.*,(SELECT COUNT(*) FROM products p WHERE p.default_supplier_id=s.id) product_count,(SELECT COUNT(*) FROM purchases pu WHERE pu.supplier_id=s.id) purchase_count FROM suppliers s WHERE $ws ORDER BY s.name LIMIT $per OFFSET $off");$st->execute($params);$suppliers=$st->fetchAll();
$pageTitle='Suppliers';$pageStyles=['admin.css','commerce.css'];require BASE_PATH.'/includes/header.php';require BASE_PATH.'/includes/sidebar.php';
?>
<div class="app-main"><?php require BASE_PATH.'/includes/navbar.php';?><main class="content"><?php require BASE_PATH.'/includes/alerts.php';?><div class="page-toolbar"><div><span class="eyebrow">Purchasing</span><h2>Suppliers</h2><p>Manage vendors and their purchasing history.</p></div><?php if(user_can('suppliers.manage')):?><a class="button button--primary" href="<?=e(app_url('suppliers/add'))?>">+ Add supplier</a><?php endif;?></div>
<section class="panel-card table-panel"><form method="get" class="filter-bar"><div class="filter-search"><input type="search" name="q" value="<?=e($q)?>" placeholder="Search supplier, contact, phone or email"></div><select name="status"><option value="active" <?=$status==='active'?'selected':''?>>Active</option><option value="inactive" <?=$status==='inactive'?'selected':''?>>Inactive</option><option value="all" <?=$status==='all'?'selected':''?>>All</option></select><button class="button button--secondary">Filter</button></form><div class="table-wrap"><table class="data-table"><thead><tr><th>Supplier</th><th>Contact</th><th>Products</th><th>Purchases</th><th>Status</th><th></th></tr></thead><tbody><?php if(!$suppliers):?><tr><td colspan="6"><div class="empty-state"><strong>No suppliers found</strong></div></td></tr><?php else:foreach($suppliers as $s):?><tr><td><strong><?=e($s['name'])?></strong><small class="table-note"><?=e($s['tax_number']?:'No tax number')?></small></td><td><?=e($s['contact_person']?:'—')?><small class="table-note"><?=e($s['phone']?:$s['email']?:'—')?></small></td><td><?=e((string)$s['product_count'])?></td><td><?=e((string)$s['purchase_count'])?></td><td><span class="status-badge status-badge--<?=e($s['status'])?>"><?=e(ucfirst($s['status']))?></span></td><td class="table-action-cell"><a class="table-action" href="<?=e(app_url('suppliers/view?id='.(int)$s['id']))?>">View</a></td></tr><?php endforeach;endif;?></tbody></table></div><div class="table-footer"><span>Showing <?=$total===0?0:$off+1?>–<?=min($off+$per,$total)?> of <?=$total?></span></div></section></main></div><?php require BASE_PATH.'/includes/footer.php';?>
