<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/config/bootstrap.php';
require_permission('products.create');

/**
 * Generate the next numeric SKU.
 *
 * Examples:
 * 001 -> 002
 * 009 -> 010
 * 099 -> 100
 * 999 -> 1000
 *
 * Non-numeric SKUs are ignored so the automatic sequence remains predictable.
 */
function generate_next_product_sku(PDO $pdo, bool $lockRow = false): string
{
    $sql =
        'SELECT sku
         FROM products
         WHERE sku REGEXP "^[0-9]+$"
         ORDER BY CAST(sku AS UNSIGNED) DESC
         LIMIT 1';

    if ($lockRow) {
        $sql .= ' FOR UPDATE';
    }

    $stmt = $pdo->query($sql);
    $previousSku = $stmt->fetchColumn();

    if ($previousSku === false || $previousSku === null || $previousSku === '') {
        return '001';
    }

    $previousSku = (string) $previousSku;
    $width = max(3, strlen($previousSku));
    $nextNumber = ((int) $previousSku) + 1;

    return str_pad((string) $nextNumber, $width, '0', STR_PAD_LEFT);
}

$pdo = db();

$categories = $pdo->query(
    'SELECT id, name
     FROM categories
     WHERE status = "active"
     ORDER BY name'
)->fetchAll();

$units = $pdo->query(
    'SELECT id, name, short_name, allows_decimal
     FROM units
     WHERE is_active = 1
     ORDER BY name'
)->fetchAll();

$suppliers = $pdo->query(
    'SELECT id, name
     FROM suppliers
     WHERE status = "active"
     ORDER BY name'
)->fetchAll();

$data = [
    'name' => '',
    'sku' => generate_next_product_sku($pdo),
    'barcode' => '',
    'category_id' => '',
    'unit_id' => '',
    'description' => '',
    'buying_price' => '0.00',
    'selling_price' => '0.00',
    'minimum_stock' => '0.000',
    'opening_stock' => '0.000',
    'default_supplier_id' => '',
    'track_stock' => 1,
    'status' => 'active',
];

$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_valid_csrf();

    /*
     * SKU is intentionally NOT accepted from POST.
     * It is generated by the server so users cannot manually alter the sequence.
     */
    foreach (array_keys($data) as $key) {
        if ($key === 'track_stock' || $key === 'sku') {
            continue;
        }

        $data[$key] = trim((string) ($_POST[$key] ?? ''));
    }

    $data['track_stock'] = isset($_POST['track_stock']) ? 1 : 0;
    $data['barcode'] = trim($data['barcode']);

    if (mb_strlen($data['name']) < 2 || mb_strlen($data['name']) > 180) {
        $errors['name'] = 'Enter a product name.';
    }

    if (!in_array($data['status'], ['active', 'inactive'], true)) {
        $errors['status'] = 'Invalid product status.';
    }

    try {
        $buyingCents = money_to_cents($data['buying_price']);
        $sellingCents = money_to_cents($data['selling_price']);
        $minimumMilli = quantity_to_milli($data['minimum_stock']);
        $openingMilli = quantity_to_milli($data['opening_stock']);

        if (
            $buyingCents < 0 ||
            $sellingCents < 0 ||
            $minimumMilli < 0 ||
            $openingMilli < 0
        ) {
            throw new InvalidArgumentException();
        }
    } catch (Throwable) {
        $errors['buying_price'] = 'Prices and quantities must be valid non-negative numbers.';
        $buyingCents = 0;
        $sellingCents = 0;
        $minimumMilli = 0;
        $openingMilli = 0;
    }

    $categoryStmt = $pdo->prepare(
        'SELECT id
         FROM categories
         WHERE id = :id
           AND status = "active"'
    );
    $categoryStmt->execute([':id' => (int) $data['category_id']]);

    if (!$categoryStmt->fetchColumn()) {
        $errors['category_id'] = 'Choose a valid category.';
    }

    $unitStmt = $pdo->prepare(
        'SELECT id, allows_decimal
         FROM units
         WHERE id = :id
           AND is_active = 1'
    );
    $unitStmt->execute([':id' => (int) $data['unit_id']]);
    $selectedUnit = $unitStmt->fetch();

    if (!$selectedUnit) {
        $errors['unit_id'] = 'Choose a valid unit.';
    } elseif (
        (int) $selectedUnit['allows_decimal'] === 0 &&
        $openingMilli % 1000 !== 0
    ) {
        $errors['opening_stock'] = 'This unit only accepts whole quantities.';
    }

    if ($openingMilli > 0 && !user_can('inventory.adjust')) {
        $errors['opening_stock'] = 'You do not have permission to record opening stock.';
    }

    if ($data['default_supplier_id'] !== '') {
        $supplierStmt = $pdo->prepare(
            'SELECT id
             FROM suppliers
             WHERE id = :id
               AND status = "active"'
        );
        $supplierStmt->execute([
            ':id' => (int) $data['default_supplier_id'],
        ]);

        if (!$supplierStmt->fetchColumn()) {
            $errors['default_supplier_id'] = 'Choose a valid supplier.';
        }
    }

    /*
     * Barcode remains user-entered, so only barcode uniqueness is checked here.
     * SKU uniqueness is handled automatically by the generated sequence and
     * the database UNIQUE constraint.
     */
    if ($data['barcode'] !== '') {
        $barcodeStmt = $pdo->prepare(
            'SELECT id
             FROM products
             WHERE barcode = :barcode
             LIMIT 1'
        );
        $barcodeStmt->execute([
            ':barcode' => $data['barcode'],
        ]);

        if ($barcodeStmt->fetchColumn()) {
            $errors['barcode'] = 'That barcode is already in use.';
        }
    }

    $imagePath = null;

    if (!$errors && isset($_FILES['image'])) {
        try {
            $imagePath = save_product_image($_FILES['image']);
        } catch (Throwable $e) {
            $errors['image'] = $e->getMessage();
        }
    }

    if (!$errors) {
        try {
            $pdo->beginTransaction();

            /*
             * Recalculate inside the transaction.
             *
             * The SKU displayed when the page loaded is only a preview.
             * This transaction-time value is the authoritative SKU in case
             * another product was added before this form was submitted.
             */
            $data['sku'] = generate_next_product_sku($pdo, true);

            $insert = $pdo->prepare(
                'INSERT INTO products
                 (
                    category_id,
                    unit_id,
                    default_supplier_id,
                    name,
                    sku,
                    barcode,
                    description,
                    buying_price,
                    average_cost,
                    selling_price,
                    minimum_stock,
                    current_stock,
                    image_path,
                    track_stock,
                    status,
                    created_by
                 )
                 VALUES
                 (
                    :category_id,
                    :unit_id,
                    :supplier_id,
                    :name,
                    :sku,
                    :barcode,
                    :description,
                    :buying_price,
                    :average_cost,
                    :selling_price,
                    :minimum_stock,
                    :current_stock,
                    :image_path,
                    :track_stock,
                    :status,
                    :created_by
                 )'
            );

            $insert->execute([
                ':category_id' => (int) $data['category_id'],
                ':unit_id' => (int) $data['unit_id'],
                ':supplier_id' => $data['default_supplier_id'] !== ''
                    ? (int) $data['default_supplier_id']
                    : null,
                ':name' => $data['name'],
                ':sku' => $data['sku'],
                ':barcode' => $data['barcode'] !== ''
                    ? $data['barcode']
                    : null,
                ':description' => $data['description'] !== ''
                    ? $data['description']
                    : null,
                ':buying_price' => cents_to_decimal($buyingCents),
                ':average_cost' => cents_to_decimal($buyingCents),
                ':selling_price' => cents_to_decimal($sellingCents),
                ':minimum_stock' => milli_to_decimal($minimumMilli),
                ':current_stock' => $data['track_stock']
                    ? milli_to_decimal($openingMilli)
                    : '0.000',
                ':image_path' => $imagePath,
                ':track_stock' => $data['track_stock'],
                ':status' => $data['status'],
                ':created_by' => (int) current_user()['id'],
            ]);

            $productId = (int) $pdo->lastInsertId();

            if ($data['track_stock'] && $openingMilli > 0) {
                $movement = $pdo->prepare(
                    'INSERT INTO stock_movements
                     (
                        branch_id,
                        product_id,
                        movement_type,
                        reference_type,
                        reference_id,
                        reference_no,
                        quantity_change,
                        unit_cost,
                        stock_before,
                        stock_after,
                        reason,
                        created_by
                     )
                     VALUES
                     (
                        :branch_id,
                        :product_id,
                        "opening_stock",
                        "product",
                        :reference_id,
                        :reference_no,
                        :quantity,
                        :unit_cost,
                        0.000,
                        :stock_after,
                        :reason,
                        :created_by
                     )'
                );

                $movement->execute([
                    ':branch_id' => current_branch_id(),
                    ':product_id' => $productId,
                    ':reference_id' => $productId,
                    ':reference_no' => $data['sku'],
                    ':quantity' => milli_to_decimal($openingMilli),
                    ':unit_cost' => units4_to_decimal($buyingCents * 100),
                    ':stock_after' => milli_to_decimal($openingMilli),
                    ':reason' => 'Opening stock',
                    ':created_by' => (int) current_user()['id'],
                ]);
            }

            $pdo->commit();

            audit_log(
                'product_created',
                'products',
                $productId,
                'Product created: ' . $data['name'] . '.',
                null,
                [
                    'sku' => $data['sku'],
                    'opening_stock' => milli_to_decimal($openingMilli),
                ]
            );

            flash(
                'success',
                'Product added successfully with SKU ' . $data['sku'] . '.'
            );

            redirect('products/view?id=' . $productId);
        } catch (Throwable $e) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }

            if ($imagePath) {
                $file = BASE_PATH . '/' . $imagePath;

                if (is_file($file)) {
                    @unlink($file);
                }
            }

            error_log('Product create failed: ' . $e->getMessage());

            /*
             * Refresh the preview SKU after a failed save attempt.
             */
            $data['sku'] = generate_next_product_sku($pdo);

            $errors['general'] = 'The product could not be saved. Please try again.';
        }
    }
}

$pageTitle = 'Add Product';
$pageStyles = ['admin.css', 'commerce.css'];

require BASE_PATH . '/includes/header.php';
require BASE_PATH . '/includes/sidebar.php';

$isEdit = false;
?>
<div class="app-main">
    <?php require BASE_PATH . '/includes/navbar.php'; ?>

    <main class="content">
        <div class="page-toolbar">
            <div>
                <a class="back-link" href="<?= e(app_url('products/index')) ?>">
                    ← Back to products
                </a>
                <h2>Add product</h2>
                <p>Create a product and optionally record its opening stock.</p>
            </div>
        </div>

        <?php if (isset($errors['general'])): ?>
            <div class="app-alert app-alert--danger">
                <?= e($errors['general']) ?>
            </div>
        <?php endif; ?>

        <form method="post" enctype="multipart/form-data" class="form-card">
            <?= csrf_field() ?>

            <?php require __DIR__ . '/_form.php'; ?>

            <div class="form-actions">
                <a class="button button--ghost" href="<?= e(app_url('products/index')) ?>">
                    Cancel
                </a>
                <button class="button button--primary" type="submit">
                    Save product
                </button>
            </div>
        </form>
    </main>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const skuInput = document.querySelector('input[name="sku"]');

    if (!skuInput) {
        return;
    }

    skuInput.value = <?= json_encode($data['sku']) ?>;
    skuInput.readOnly = true;
    skuInput.setAttribute('aria-readonly', 'true');
    skuInput.setAttribute('title', 'SKU is generated automatically');
    skuInput.style.cursor = 'not-allowed';
});
</script>

<?php require BASE_PATH . '/includes/footer.php'; ?>
