<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php'; require_permission('products.update');
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 require_valid_csrf(); $action=(string)($_POST['action']??'');
 if($action==='category_create'){
  $name=trim((string)($_POST['name']??''));$description=trim((string)($_POST['description']??''));$parent=(int)($_POST['parent_id']??0);$slug=slugify($name);
  if(mb_strlen($name)<2||$slug==='')$errors['category']='Enter a valid category name.';
  $check=db()->prepare('SELECT COUNT(*) FROM categories WHERE name=:name OR slug=:slug');$check->execute([':name'=>$name,':slug'=>$slug]);if((int)$check->fetchColumn()>0)$errors['category']='That category already exists.';
  if(!$errors){$st=db()->prepare('INSERT INTO categories(parent_id,name,slug,description,status,created_by) VALUES(:parent,:name,:slug,:description,"active",:user)');$st->execute([':parent'=>$parent>0?$parent:null,':name'=>$name,':slug'=>$slug,':description'=>$description?:null,':user'=>(int)current_user()['id']]);audit_log('category_created','products',(int)db()->lastInsertId(),'Category created: '.$name.'.');flash('success','Category created.');redirect('products/categories.php');}
 }
 if($action==='category_toggle'){$id=(int)($_POST['id']??0);$st=db()->prepare('SELECT id,name,status FROM categories WHERE id=:id');$st->execute([':id'=>$id]);$row=$st->fetch();if($row){$new=$row['status']==='active'?'inactive':'active';$up=db()->prepare('UPDATE categories SET status=:s WHERE id=:id');$up->execute([':s'=>$new,':id'=>$id]);audit_log('category_updated','products',$id,'Category status changed: '.$row['name'].'.');flash('success','Category status updated.');}redirect('products/categories.php');}
 if($action==='unit_create'){
  $name=trim((string)($_POST['unit_name']??''));$short=mb_strtolower(trim((string)($_POST['short_name']??'')));$decimal=isset($_POST['allows_decimal'])?1:0;$places=$decimal?min(3,max(1,(int)($_POST['decimal_places']??3))):0;
  if(mb_strlen($name)<2||$short==='')$errors['unit']='Enter a unit name and short name.';
  $check=db()->prepare('SELECT COUNT(*) FROM units WHERE short_name=:s');$check->execute([':s'=>$short]);if((int)$check->fetchColumn()>0)$errors['unit']='That unit short name already exists.';
  if(!$errors){$st=db()->prepare('INSERT INTO units(name,short_name,allows_decimal,decimal_places,is_active) VALUES(:n,:s,:d,:p,1)');$st->execute([':n'=>$name,':s'=>$short,':d'=>$decimal,':p'=>$places]);flash('success','Unit created.');redirect('products/categories.php');}
 }
 if($action==='unit_toggle'){$id=(int)($_POST['id']??0);$up=db()->prepare('UPDATE units SET is_active=IF(is_active=1,0,1) WHERE id=:id');$up->execute([':id'=>$id]);flash('success','Unit status updated.');redirect('products/categories.php');}
}
$categories=db()->query('SELECT c.*,p.name parent_name,(SELECT COUNT(*) FROM products pr WHERE pr.category_id=c.id) product_count FROM categories c LEFT JOIN categories p ON p.id=c.parent_id ORDER BY c.name')->fetchAll();
$units=db()->query('SELECT u.*,(SELECT COUNT(*) FROM products p WHERE p.unit_id=u.id) product_count FROM units u ORDER BY u.name')->fetchAll();
$pageTitle='Categories & Units';$pageStyles=['admin.css','commerce.css'];require BASE_PATH.'/includes/header.php';require BASE_PATH.'/includes/sidebar.php';
?>
<div class="app-main"><?php require BASE_PATH.'/includes/navbar.php';?><main class="content"><?php require BASE_PATH.'/includes/alerts.php';?><div class="page-toolbar"><div><a class="back-link" href="<?=e(app_url('products/index.php'))?>">← Products</a><h2>Categories & units</h2><p>Configure how products are grouped and measured.</p></div></div>
<div class="master-data-grid">
<section class="panel-card"><div class="panel-card__header"><span class="eyebrow">Categories</span><h3>Product categories</h3></div><form method="post" class="inline-create-form"><?=csrf_field()?><input type="hidden" name="action" value="category_create"><input name="name" placeholder="Category name" required><select name="parent_id"><option value="0">No parent</option><?php foreach($categories as $c):?><option value="<?=e((string)$c['id'])?>"><?=e($c['name'])?></option><?php endforeach;?></select><input name="description" placeholder="Description (optional)"><button class="button button--primary" type="submit">Add</button></form><?php if(isset($errors['category'])):?><div class="inline-error"><?=e($errors['category'])?></div><?php endif;?><div class="simple-list"><?php foreach($categories as $c):?><div class="simple-list__row"><div><strong><?=e($c['name'])?></strong><span><?=e($c['parent_name']?'Under '.$c['parent_name']:(string)$c['product_count'].' products')?></span></div><div class="row-actions"><span class="status-badge status-badge--<?=e($c['status'])?>"><?=e(ucfirst($c['status']))?></span><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="category_toggle"><input type="hidden" name="id" value="<?=e((string)$c['id'])?>"><button class="link-button" type="submit"><?= $c['status']==='active'?'Disable':'Enable'?></button></form></div></div><?php endforeach;?></div></section>
<section class="panel-card"><div class="panel-card__header"><span class="eyebrow">Units</span><h3>Selling units</h3></div><form method="post" class="unit-create-form"><?=csrf_field()?><input type="hidden" name="action" value="unit_create"><div class="field"><label>Unit name</label><input name="unit_name" placeholder="e.g. Yard" required></div><div class="field"><label>Short name</label><input name="short_name" placeholder="yd" required></div><label class="checkbox-row"><input type="checkbox" name="allows_decimal" value="1" checked> Allow decimal quantities</label><div class="field"><label>Decimal places</label><select name="decimal_places"><option value="1">1</option><option value="2">2</option><option value="3" selected>3</option></select></div><button class="button button--primary" type="submit">Add unit</button></form><?php if(isset($errors['unit'])):?><div class="inline-error"><?=e($errors['unit'])?></div><?php endif;?><div class="simple-list"><?php foreach($units as $u):?><div class="simple-list__row"><div><strong><?=e($u['name'])?> (<?=e($u['short_name'])?>)</strong><span><?= (int)$u['allows_decimal']===1?'Decimals allowed':'Whole quantities only'?> · <?=e((string)$u['product_count'])?> products</span></div><div class="row-actions"><span class="status-badge status-badge--<?= (int)$u['is_active']===1?'active':'inactive'?>"><?= (int)$u['is_active']===1?'Active':'Inactive'?></span><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="unit_toggle"><input type="hidden" name="id" value="<?=e((string)$u['id'])?>"><button class="link-button" type="submit"><?= (int)$u['is_active']===1?'Disable':'Enable'?></button></form></div></div><?php endforeach;?></div></section>
</div></main></div><?php require BASE_PATH.'/includes/footer.php';?>
