<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php'; require_permission('products.view');
$id=max(0,(int)($_GET['id']??0));
$stmt=db()->prepare('SELECT p.*,c.name category_name,u.name unit_name,u.short_name,u.allows_decimal,s.name supplier_name FROM products p INNER JOIN categories c ON c.id=p.category_id INNER JOIN units u ON u.id=p.unit_id LEFT JOIN suppliers s ON s.id=p.default_supplier_id WHERE p.id=:id LIMIT 1'); $stmt->execute([':id'=>$id]); $p=$stmt->fetch();
if(!$p){flash('error','Product not found.');redirect('products/index.php');}
$mov=db()->prepare('SELECT sm.*,u.full_name FROM stock_movements sm INNER JOIN users u ON u.id=sm.created_by WHERE sm.product_id=:id ORDER BY sm.id DESC LIMIT 12');$mov->execute([':id'=>$id]);$movements=$mov->fetchAll();
$stats=db()->prepare('SELECT COALESCE(SUM(CASE WHEN quantity_change>0 THEN quantity_change ELSE 0 END),0) stock_in, COALESCE(ABS(SUM(CASE WHEN quantity_change<0 THEN quantity_change ELSE 0 END)),0) stock_out FROM stock_movements WHERE product_id=:id');$stats->execute([':id'=>$id]);$stockStats=$stats->fetch()?:[];
$pageTitle=$p['name'];$pageStyles=['admin.css','commerce.css'];require BASE_PATH.'/includes/header.php';require BASE_PATH.'/includes/sidebar.php';
?>
<div class="app-main"><?php require BASE_PATH.'/includes/navbar.php';?><main class="content"><?php require BASE_PATH.'/includes/alerts.php';?>
<div class="page-toolbar"><div><a class="back-link" href="<?=e(app_url('products/index.php'))?>">← Products</a><h2><?=e($p['name'])?></h2><p><?=e($p['sku'])?> · <?=e($p['category_name'])?></p></div><div class="toolbar-actions"><?php if(user_can('inventory.adjust')):?><a class="button button--secondary" href="<?=e(app_url('inventory/stock_adjustment.php?product='.$id))?>">Adjust stock</a><?php endif;?><?php if(user_can('products.update')):?><a class="button button--primary" href="<?=e(app_url('products/edit.php?id='.$id))?>">Edit product</a><?php endif;?></div></div>
<section class="product-detail-grid">
<article class="panel-card product-hero"><div class="product-large-image"><?php if($p['image_path']):?><img src="<?=e(app_url($p['image_path']))?>" alt="<?=e($p['name'])?>"><?php else:?><span><?=e(initials($p['name']))?></span><?php endif;?></div><div><span class="status-badge status-badge--<?=e($p['status'])?>"><?=e(ucfirst($p['status']))?></span><h3><?=e($p['name'])?></h3><p><?=nl2br(e($p['description']?:'No description added.'))?></p><div class="detail-pills"><span>SKU: <?=e($p['sku'])?></span><?php if($p['barcode']):?><span>Barcode: <?=e($p['barcode'])?></span><?php endif;?><span><?=e($p['unit_name'])?></span></div></div></article>
<div class="metric-stack"><article class="metric-card"><div class="metric-card__top"><span>Current stock</span></div><strong><?=e(format_quantity($p['current_stock']))?> <?=e($p['short_name'])?></strong><small>Minimum: <?=e(format_quantity($p['minimum_stock']))?> <?=e($p['short_name'])?></small></article><article class="metric-card"><div class="metric-card__top"><span>Selling price</span></div><strong><?=e(money($p['selling_price']))?></strong><small>per <?=e($p['short_name'])?></small></article><article class="metric-card"><div class="metric-card__top"><span>Average cost</span></div><strong><?=e(money($p['average_cost']))?></strong><small>Stock value <?=e(money((string)((float)$p['current_stock']*(float)$p['average_cost'])))?></small></article></div>
</section>
<section class="panel-card table-panel section-gap"><div class="panel-card__header panel-card__header--row"><div><span class="eyebrow">Inventory ledger</span><h3>Recent stock movements</h3></div><a class="table-action" href="<?=e(app_url('inventory/stock_history.php?product='.$id))?>">Full history</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Movement</th><th>Change</th><th>Before</th><th>After</th><th>Reference</th><th>User</th></tr></thead><tbody><?php if(!$movements):?><tr><td colspan="7"><div class="empty-state"><strong>No stock movements yet</strong></div></td></tr><?php else:foreach($movements as $m):?><tr><td><?=e(format_datetime($m['created_at']))?></td><td><?=e(ucwords(str_replace('_',' ',$m['movement_type'])))?></td><td class="<?=((float)$m['quantity_change']>=0?'text-success':'text-danger')?>"><?=((float)$m['quantity_change']>=0?'+':'')?><?=e(format_quantity($m['quantity_change']))?> <?=e($p['short_name'])?></td><td><?=e(format_quantity($m['stock_before']))?></td><td><?=e(format_quantity($m['stock_after']))?></td><td><?=e($m['reference_no']?:'—')?></td><td><?=e($m['full_name'])?></td></tr><?php endforeach;endif;?></tbody></table></div></section>
</main></div><?php require BASE_PATH.'/includes/footer.php';?>
