<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
require_permission('pos.hold');
if ($_SERVER['REQUEST_METHOD'] !== 'POST') json_response(['ok'=>false,'message'=>'Method not allowed.'],405);
$payload=json_input();require_json_csrf($payload);$rawItems=$payload['items']??[];$customerId=max(0,(int)($payload['customer_id']??0));$heldId=max(0,(int)($payload['held_sale_id']??0));$notes=trim((string)($payload['notes']??''));if(!is_array($rawItems)||!$rawItems)json_response(['ok'=>false,'message'=>'The cart is empty.'],422);$pdo=db();
try{$pdo->beginTransaction();$saleNo='';if($heldId>0){$h=$pdo->prepare('SELECT id,sale_no FROM sales WHERE id=:id AND status="held" FOR UPDATE');$h->execute([':id'=>$heldId]);$held=$h->fetch();if(!$held)throw new RuntimeException('Held sale is unavailable.');$saleNo=$held['sale_no'];}else{$saleNo=next_document_number($pdo,'sale');}
if($customerId>0){$c=$pdo->prepare('SELECT id FROM customers WHERE id=:id AND status="active"');$c->execute([':id'=>$customerId]);if(!$c->fetchColumn())throw new RuntimeException('Selected customer is unavailable.');}
$items=[];$subtotal=0;$discount=0;$total=0;$cogs=0;$seen=[];foreach($rawItems as$raw){if(!is_array($raw))continue;$pid=(int)($raw['product_id']??0);if($pid<=0)continue;if(isset($seen[$pid]))throw new RuntimeException('A product appears more than once.');$seen[$pid]=1;$p=$pdo->prepare('SELECT p.id,p.name,p.sku,p.selling_price,p.average_cost,u.short_name,u.allows_decimal FROM products p INNER JOIN units u ON u.id=p.unit_id WHERE p.id=:id AND p.status="active"');$p->execute([':id'=>$pid]);$product=$p->fetch();if(!$product)throw new RuntimeException('One product is unavailable.');$q=quantity_to_milli((string)($raw['quantity']??'0'));if($q<=0)throw new RuntimeException('Quantity must be greater than zero.');if((int)$product['allows_decimal']===0&&$q%1000!==0)throw new RuntimeException($product['name'].' accepts whole quantities only.');$standard=money_to_cents($product['selling_price']);$requested=money_to_cents((string)($raw['unit_price']??$product['selling_price']));$price=user_can('pos.price_override')?$requested:$standard;$lineSub=line_total_cents($q,$price);$disc=user_can('pos.discount')?money_to_cents((string)($raw['discount_amount']??0)):0;if($disc<0||$disc>$lineSub)throw new RuntimeException('Invalid line discount.');$line=$lineSub-$disc;$cost4=decimal4_to_units($product['average_cost']);$lineCogs=line_cost_cents($q,$cost4);$subtotal+=$lineSub;$discount+=$disc;$total+=$line;$cogs+=$lineCogs;$items[]=['product'=>$product,'q'=>$q,'price'=>$price,'cost4'=>$cost4,'discount'=>$disc,'line'=>$line,'cogs'=>$lineCogs,'profit'=>$line-$lineCogs];}
if(!$items)throw new RuntimeException('The cart has no valid items.');$profit=$total-$cogs;if($heldId>0){$up=$pdo->prepare('UPDATE sales SET customer_id=:customer,sale_date=NOW(),subtotal=:subtotal,discount_amount=:discount,total_amount=:total,cogs_amount=:cogs,gross_profit=:profit,amount_paid=0.00,balance_due=:balance,payment_status="unpaid",notes=:notes WHERE id=:id');$up->execute([':customer'=>$customerId?:null,':subtotal'=>cents_to_decimal($subtotal),':discount'=>cents_to_decimal($discount),':total'=>cents_to_decimal($total),':cogs'=>cents_to_decimal($cogs),':profit'=>cents_to_decimal($profit),':balance'=>cents_to_decimal($total),':notes'=>$notes?:null,':id'=>$heldId]);$saleId=$heldId;$pdo->prepare('DELETE FROM sale_items WHERE sale_id=:id')->execute([':id'=>$saleId]);}else{$ins=$pdo->prepare('INSERT INTO sales(branch_id,sale_no,customer_id,sale_date,status,payment_status,subtotal,discount_amount,total_amount,cogs_amount,gross_profit,amount_paid,balance_due,change_due,notes,created_by) VALUES(:branch,:no,:customer,NOW(),"held","unpaid",:subtotal,:discount,:total,:cogs,:profit,0.00,:balance,0.00,:notes,:user)');$ins->execute([':branch'=>current_branch_id(),':no'=>$saleNo,':customer'=>$customerId?:null,':subtotal'=>cents_to_decimal($subtotal),':discount'=>cents_to_decimal($discount),':total'=>cents_to_decimal($total),':cogs'=>cents_to_decimal($cogs),':profit'=>cents_to_decimal($profit),':balance'=>cents_to_decimal($total),':notes'=>$notes?:null,':user'=>(int)current_user()['id']]);$saleId=(int)$pdo->lastInsertId();}
foreach($items as$i){$si=$pdo->prepare('INSERT INTO sale_items(sale_id,product_id,product_name_snapshot,sku_snapshot,unit_snapshot,quantity,unit_price,cost_price,discount_amount,line_total,cogs_amount,profit_amount) VALUES(:sale,:product,:name,:sku,:unit,:q,:price,:cost,:discount,:total,:cogs,:profit)');$si->execute([':sale'=>$saleId,':product'=>(int)$i['product']['id'],':name'=>$i['product']['name'],':sku'=>$i['product']['sku'],':unit'=>$i['product']['short_name'],':q'=>milli_to_decimal($i['q']),':price'=>cents_to_decimal($i['price']),':cost'=>units4_to_decimal($i['cost4']),':discount'=>cents_to_decimal($i['discount']),':total'=>cents_to_decimal($i['line']),':cogs'=>cents_to_decimal($i['cogs']),':profit'=>cents_to_decimal($i['profit'])]);}
transactional_audit($pdo,'sale_held','sales',$saleId,'Sale held: '.$saleNo.'.',null,['total'=>cents_to_decimal($total)]);$pdo->commit();json_response(['ok'=>true,'sale_id'=>$saleId,'sale_no'=>$saleNo]);
}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();error_log('Hold sale failed: '.$e->getMessage());json_response(['ok'=>false,'message'=>$e instanceof RuntimeException?$e->getMessage():'Sale could not be held.'],422);}
